/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ErdRouteImport } from './routes/erd'
import { Route as IndexRouteImport } from './routes/index'

const ErdRoute = ErdRouteImport.update({
  id: '/erd',
  path: '/erd',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/erd': typeof ErdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/erd': typeof ErdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/erd': typeof ErdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/erd'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/erd'
  id: '__root__' | '/' | '/erd'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErdRoute: typeof ErdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/erd': {
      id: '/erd'
      path: '/erd'
      fullPath: '/erd'
      preLoaderRoute: typeof ErdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErdRoute: ErdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
